version: '2'

services:
  wildcat:
    dns_search:
      - www.example.dev
    extends:
      file: ./docker-compose.yml
      service: wildcat
    build:
      context: .
      args:
        JSPM_GITHUB_AUTH_TOKEN:
    links:
      - "static:static.example.dev"
    ports:
      - "3000:3000"
    entrypoint: "npm run"
    command: "prod"

  static:
    dns_search:
      - static.example.dev
    extends:
      file: ./docker-compose.yml
      service: wildcat
    build:
      context: .
      args:
        JSPM_GITHUB_AUTH_TOKEN:
    environment:
      STATIC_HOST: static.example.dev
    ports:
      - "4000:4000"
    entrypoint: "npm run"
    command: "prod-static"

