version: '2'

services:
  wildcat:
    depends_on:
      - selenium
    dns_search:
      - static.example.dev
      - www.example.dev
    # extra_hosts:
    #   - "static.example.dev:127.0.0.1"
    networks:
      default:
        aliases:
          - www.example.dev
          - static.example.dev
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./src:/code/src
      - ./api:/code/api

  selenium:
    dns_search:
      - selenium.example.dev
    build:
      context: ./ssl
    image: nfl/standalone-chrome-debug:2.52.0
    environment:
      no_proxy: ""
    volumes:
      - /tmp:/e2e/uploads
    ports:
      - "4444:4444"
      - "6900:5900"

  dnsmasq:
    image: andyshinn/dnsmasq:2.76
    restart: always
    ports:
      - "53535:53"
      - "53535:53/udp"
    cap_add:
      - NET_ADMIN
    command: "--log-facility=- --address=/dev/127.0.0.1"
