version: '2'

services:
  wildcat:
    depends_on:
      - selenium
    dns_search:
      - static.example.localhost
      - www.example.localhost
    extra_hosts:
      - "static.example.localhost:127.0.0.1"
    networks:
      default:
        aliases:
          - www.example.localhost
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./src:/code/src
      - ./api:/code/api

  selenium:
    dns_search:
      - selenium.example.localhost
    build:
      context: ./ssl
    image: nfl/standalone-chrome-debug:2.52.0
    environment:
      no_proxy: localhost
    volumes:
      - /dev/urandom:/dev/random
    ports:
      - "4444:4444"
      - "6900:5900"
